[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr", "hydration"] }
yew-router = "0.18.0"
gloo = "0.11.0"
wasm-bindgen-futures = "0.4.43"